/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schedule;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ahmed
 */
public class ForgotMyPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotMyPassword
     */
    public ForgotMyPassword() {
        super("Forgot My Password");

        initComponents();

        setLocationRelativeTo(null);

        tf_username.setText(Login.tf_username.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pm_forgotmypassword = new javax.swing.JPopupMenu();
        mi_color = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinner_age = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cb_smoking = new javax.swing.JCheckBox();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        cb_department = new javax.swing.JComboBox<>();
        btn_accept = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb_grade = new javax.swing.JComboBox<>();

        pm_forgotmypassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pm_forgotmypasswordMouseClicked(evt);
            }
        });

        mi_color.setText("Change Color");
        mi_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_colorActionPerformed(evt);
            }
        });
        pm_forgotmypassword.add(mi_color);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ForgotMyPassword", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mail");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Age");

        spinner_age.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Smoking");

        cb_smoking.setBackground(new java.awt.Color(255, 255, 255));
        cb_smoking.setText("Yes");

        buttonGroup1.add(rb_male);
        rb_male.setText("Male");

        buttonGroup1.add(rb_female);
        rb_female.setText("Female");

        cb_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Engineering", "Doctor", "Economy", "Dentist" }));
        cb_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_departmentActionPerformed(evt);
            }
        });

        btn_accept.setText("Accept");
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });

        jLabel6.setText("Gender");

        jLabel7.setText("Department");

        jLabel1.setText("Grade");

        cb_grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(37, 37, 37)
                            .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(74, 74, 74)
                            .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(76, 76, 76)
                            .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(45, 45, 45)
                            .addComponent(cb_smoking))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rb_male)
                                    .addGap(48, 48, 48)
                                    .addComponent(rb_female))
                                .addComponent(cb_grade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(cb_smoking))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(rb_male)
                    .addComponent(rb_female))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btn_accept)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Checking some equalizations for all fields.
    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed

        if (!Regex.validateForgotMyPasswordUsername(tf_username.getText())) {
            return;
        }

        if (!Regex.validateForgotMyPasswordMail(tf_mail.getText())) {
            return;
        }

        if ((!tf_username.getText().isEmpty())) { //Checking for username field to avoid from empty field.
            if ((!tf_mail.getText().isEmpty())) {
                if (cb_smoking.isSelected()) {
                    if (rb_male.isSelected()) {
                        try {
                            //Showing the user his password with JOptionPane.
                            Db.forgotMyPassword((Integer) spinner_age.getValue(), tf_username.getText(), tf_mail.getText(), "Smoking", "Male", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(ForgotMyPassword.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else if (rb_female.isSelected()) {
                        try {
                            //Showing the user his password with JOptionPane.
                            Db.forgotMyPassword((Integer) spinner_age.getValue(), tf_username.getText(), tf_mail.getText(), "Smoking", "Female", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(ForgotMyPassword.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "You should choose your gender", "Warning !", WIDTH);
                    }
                } else {
                    if (rb_male.isSelected()) {
                        try {
                            //Showing the user his password with JOptionPane.
                            Db.forgotMyPassword((Integer) spinner_age.getValue(), tf_username.getText(), tf_mail.getText(), "Not Smoking", "Male", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(ForgotMyPassword.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else if (rb_female.isSelected()) {
                        try {
                            //Showing the user his password with JOptionPane.
                            Db.forgotMyPassword((Integer) spinner_age.getValue(), tf_username.getText(), tf_mail.getText(), "Not Smoking", "Female", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(ForgotMyPassword.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "You should choose your gender", "Warning !", WIDTH);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mail field cannot be empty", "Warning !", WIDTH);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Username field cannot be empty", "Warning !", WIDTH);
        }
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void pm_forgotmypasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_forgotmypasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pm_forgotmypasswordMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            pm_forgotmypassword.show(this, evt.getX() + 20, evt.getY() + 50);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    // Creating a color object from JColorChooser class.
    private void mi_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_colorActionPerformed
        Color initialcolor = Color.RED;
        Color color = JColorChooser.showDialog(this, "Select a color", initialcolor);
        jPanel1.setBackground(color);
    }//GEN-LAST:event_mi_colorActionPerformed

    //Adding specific grades into Grade Combobox if the user selects other departments.
    private void cb_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_departmentActionPerformed

        if (cb_department.getSelectedItem().toString().equals("Doctor")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
            cb_grade.addItem("5");
            cb_grade.addItem("6");
        } else if (cb_department.getSelectedItem().toString().equals("Economy")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
        } else if (cb_department.getSelectedItem().toString().equals("Dentist")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
            cb_grade.addItem("5");
        } else if (cb_department.getSelectedItem().toString().equals("Computer Engineering")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
        }
    }//GEN-LAST:event_cb_departmentActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_department;
    private javax.swing.JComboBox<String> cb_grade;
    private javax.swing.JCheckBox cb_smoking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mi_color;
    private javax.swing.JPopupMenu pm_forgotmypassword;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JSpinner spinner_age;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
