/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schedule;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ahmed
 */
public class Register extends javax.swing.JFrame {

    String value;

    /**
     * Creates new form Register
     */
    public Register() {
        super("Register");

        initComponents();

        setLocationRelativeTo(null);

        tf_username.setText(Login.tf_username.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pm_register = new javax.swing.JPopupMenu();
        mi_copy = new javax.swing.JMenuItem();
        mi_paste = new javax.swing.JMenuItem();
        cbmi_showpasswords = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        pf_passwordagain = new javax.swing.JPasswordField();
        cb_showpasswords = new javax.swing.JCheckBox();
        tf_mail = new javax.swing.JTextField();
        spinner_age = new javax.swing.JSpinner();
        cb_issmoking = new javax.swing.JCheckBox();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        cb_grade = new javax.swing.JComboBox<>();
        btn_register = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_department = new javax.swing.JComboBox<>();

        mi_copy.setText("Copy");
        mi_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_copyActionPerformed(evt);
            }
        });
        pm_register.add(mi_copy);

        mi_paste.setText("Paste");
        mi_paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_pasteActionPerformed(evt);
            }
        });
        pm_register.add(mi_paste);

        cbmi_showpasswords.setText("Show Passwords");
        cbmi_showpasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmi_showpasswordsActionPerformed(evt);
            }
        });
        pm_register.add(cbmi_showpasswords);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 1, 36)); // NOI18N
        jLabel1.setText("REGISTER SCREEN");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_usernameMouseClicked(evt);
            }
        });
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        cb_showpasswords.setBackground(new java.awt.Color(255, 255, 255));
        cb_showpasswords.setText("Show Passwords");
        cb_showpasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_showpasswordsActionPerformed(evt);
            }
        });

        spinner_age.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cb_issmoking.setBackground(new java.awt.Color(255, 255, 255));
        cb_issmoking.setText("Yes");

        rb_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_male);
        rb_male.setText("Male");

        rb_female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_female);
        rb_female.setText("Female");

        cb_grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Grade");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Gender");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Smoking");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Age");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Mail");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password Again");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Department");

        cb_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Engineering", "Doctor", "Economy", "Dentist" }));
        cb_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_departmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(cb_showpasswords))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(211, 211, 211)
                        .addComponent(rb_female))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_male, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_issmoking, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_department, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(pf_password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pf_passwordagain, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btn_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(pf_passwordagain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(cb_showpasswords)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_issmoking))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rb_male)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rb_female)))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn_register)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //If user choose the copy item, program assigns selected text into value variable.
    private void mi_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_copyActionPerformed
        value = tf_username.getSelectedText();
    }//GEN-LAST:event_mi_copyActionPerformed

    //If user choose the paste item, program pastes the information inside the value variable into username field.
    private void mi_pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_pasteActionPerformed
        try {
            if (!value.isEmpty()) {
                tf_username.setText(tf_username.getText() + value);
            }
        } catch (java.lang.NullPointerException e) {
            System.out.println("Empty value");
        }
    }//GEN-LAST:event_mi_pasteActionPerformed

    //If checkbox is selected, the password that user entered is shown on the screen.
    private void cbmi_showpasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmi_showpasswordsActionPerformed
        if (cbmi_showpasswords.isSelected()) {
            pf_password.setEchoChar((char) 0);
            pf_passwordagain.setEchoChar((char) 0);
        } else {
            pf_password.setEchoChar('*');
            pf_passwordagain.setEchoChar('*');
        }
    }//GEN-LAST:event_cbmi_showpasswordsActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    //Adding specific grades into Grade Combobox if the user selects other departments.
    private void cb_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_departmentActionPerformed

        if (cb_department.getSelectedItem().toString().equals("Doctor")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
            cb_grade.addItem("5");
            cb_grade.addItem("6");
        } else if (cb_department.getSelectedItem().toString().equals("Economy")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
        } else if (cb_department.getSelectedItem().toString().equals("Dentist")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
            cb_grade.addItem("5");
        } else if (cb_department.getSelectedItem().toString().equals("Computer Engineering")) {
            cb_grade.removeAllItems();
            cb_grade.addItem("1");
            cb_grade.addItem("2");
            cb_grade.addItem("3");
            cb_grade.addItem("4");
        }
    }//GEN-LAST:event_cb_departmentActionPerformed

    //Checking some equalizations for registeration fields.
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        if (!Regex.validateRegisterUsername(tf_username.getText())) {
            return;
        }

        if (!Regex.validateRegisterPassword(pf_password.getText())) {
            return;
        }

        if (!Regex.validateRegisterPasswordAgain(pf_passwordagain.getText())) {
            return;
        }

        if (!Regex.validateRegisterMail(tf_mail.getText())) {
            return;
        }

        if (pf_password.getText().equals(pf_passwordagain.getText())) { //Passwords should not be equal to each other.
            if (!tf_username.getText().equals(pf_password.getText()) && !tf_username.getText().equals(pf_passwordagain.getText())) { //Password and username should be different.
                if (cb_issmoking.isSelected()) {
                    if (rb_male.isSelected()) {
                        try {
                            //Adding student into Database.
                            Db.addStudent((Integer) spinner_age.getValue(), tf_username.getText(), pf_password.getText(), tf_mail.getText(), "Smoking", "Male", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        this.dispose();
                    } else if (rb_female.isSelected()) {
                        try {
                            //Adding student into Database.
                            Db.addStudent((Integer) spinner_age.getValue(), tf_username.getText(), pf_password.getText(), tf_mail.getText(), "Smoking", "Female", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Please select your gender", "Warning !", WIDTH);
                    }
                } else {
                    if (rb_male.isSelected()) {
                        try {
                            //Adding student into Database.
                            Db.addStudent((Integer) spinner_age.getValue(), tf_username.getText(), pf_password.getText(), tf_mail.getText(), "Not Smoking", "Male", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        this.dispose();
                    } else if (rb_female.isSelected()) {
                        try {
                            //Adding student into Database.
                            Db.addStudent((Integer) spinner_age.getValue(), tf_username.getText(), pf_password.getText(), tf_mail.getText(), "Not Smoking", "Female", cb_department.getSelectedItem().toString(), cb_grade.getSelectedItem().toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Please select your gender", "Warning !", WIDTH);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username and password cannot be equal", "Warning !", WIDTH);
                pf_password.setText("");
                pf_passwordagain.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Passwords you entered are not equal", "Warning !", WIDTH);
            pf_password.setText("");
            pf_passwordagain.setText("");
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    //If checkbox is selected, the password that user entered is shown on the screen.
    private void cb_showpasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_showpasswordsActionPerformed
        if (cb_showpasswords.isSelected()) {
            pf_password.setEchoChar((char) 0);
            pf_passwordagain.setEchoChar((char) 0);
        } else {
            pf_password.setEchoChar('*');
            pf_passwordagain.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_showpasswordsActionPerformed

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    //Shows popupmenu if the user click on the right mouse button.
    private void tf_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_usernameMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            pm_register.show(this, evt.getX() + 30, evt.getY() + 150);
        }
    }//GEN-LAST:event_tf_usernameMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_department;
    private javax.swing.JComboBox<String> cb_grade;
    private javax.swing.JCheckBox cb_issmoking;
    private javax.swing.JCheckBox cb_showpasswords;
    private javax.swing.JCheckBoxMenuItem cbmi_showpasswords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem mi_copy;
    private javax.swing.JMenuItem mi_paste;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField pf_passwordagain;
    private javax.swing.JPopupMenu pm_register;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JSpinner spinner_age;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
